name: Deploy to AWS EC2
on:
  workflow_run:
    workflows: ["Docker-Build"]  # Name of the first workflow
    types:
      - completed


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: SSH into EC2 and pull the latest image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/my-ml-app
            docker stop ml-app
            docker rm ml-app
            docker run -d --name ml-app -p 80:80 ${{ secrets.DOCKER_USERNAME }}/my-ml-app

      # - name: Copy log file from EC2 to local
      #   uses: appleboy/ssh-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.EC2_SSH_KEY }}
      #     source: /path/to/log/file/on/ec2.log  # Update with the correct path
      #     target: ./logs/ec2.log  # Update with the desired local path

      # - name: Commit and push log file
      #   run: |
      #     git config user.name "GitHub Actions"
      #     git config user.email "<your-email>@example.com"
      #     git add ./logs/ec2.log
      #     git commit -m "Add log file from EC2"
      #     git push
