name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-action@v2

      - name: Build and push Docker image
        run: |
          docker build -t my-ml-app .
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker tag my-ml-app ${{ secrets.AWS_REGISTRY_URL }}/my-ml-app
          docker push ${{ secrets.AWS_REGISTRY_URL }}/my-ml-app

      - name: SSH into EC2 and pull the latest image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.AWS_REGISTRY_URL }}/my-ml-app
            docker run -d -p 80:80 ${{ secrets.AWS_REGISTRY_URL }}/my-ml-app

      - name: Copy log file from EC2 to local
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: /path/to/log/file/on/ec2.log  # Update with the correct path
          target: ./logs/ec2.log  # Update with the desired local path

      - name: Commit and push log file
        run: |
          git config user.name "GitHub Actions"
          git config user.email "<your-email>@example.com"
          git add ./logs/ec2.log
          git commit -m "Add log file from EC2"
          git push
