name: Test

on:
    workflow_run:
      workflows: ["Build"]  # Name of the first workflow
      types:
        - completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.11  # Replace with your desired Python version

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests and save output
      run: |
        mkdir -p artifacts  # Create a directory to store artifacts
        pytest tests/test_classification_project.py > artifacts/test_output.txt  # Run the tests and save the output
      if: success()  # Only run this step if the previous steps were successful

    - name: Upload test artifacts
      uses: actions/upload-artifact@v2
      with:
        name: test-artifacts
        path: artifacts/
      if: success() # Only upload logs if the previous steps were successful
